import type { Migration } from './index.js';

/**
 * Users Board — qualitative summary cache.
 *
 * Per-day and per-user LLM summaries (topic, day digest, insights) are
 * expensive to (re)compute on every page load, so they're generated by an
 * explicit refresh (POST /admin/users-board/refresh) and cached here keyed
 * by a content hash of the source messages — a day's summary is only
 * regenerated when that day's messages actually changed.
 *
 *   day_summaries      — one row per (agent_group_id, day): what was talked
 *                        about that day, 1-2 lines.
 *   user_insights      — one row per agent_group_id: topic sentence,
 *                        what's-working / what's-stuck / satisfaction /
 *                        referral-moment / quality flags, as JSON.
 *   board_aggregate    — single row (id=1): cross-user recurring themes,
 *                        computed from all user_insights.
 */
export const migration025: Migration = {
  version: 25,
  name: 'users-board-summaries',
  up(db) {
    db.exec(`
      CREATE TABLE IF NOT EXISTS day_summaries (
        agent_group_id TEXT NOT NULL,
        day            TEXT NOT NULL,
        content_hash   TEXT NOT NULL,
        summary        TEXT NOT NULL,
        generated_at   TEXT NOT NULL,
        PRIMARY KEY (agent_group_id, day)
      );

      CREATE TABLE IF NOT EXISTS user_insights (
        agent_group_id TEXT PRIMARY KEY,
        content_hash   TEXT NOT NULL,
        topic          TEXT,
        insights_json  TEXT NOT NULL,
        generated_at   TEXT NOT NULL
      );

      CREATE TABLE IF NOT EXISTS board_aggregate (
        id             INTEGER PRIMARY KEY CHECK (id = 1),
        content_hash   TEXT NOT NULL,
        insights_json  TEXT NOT NULL,
        generated_at   TEXT NOT NULL
      );
    `);
  },
};
