import { initTestDb, closeDb, getDb } from './db/connection.js';
import { migration027 } from './db/migrations/027-whatsapp-agent-identities.js';
import { registerWhatsAppAccount } from './whatsapp-agent-identities.js';
import { afterEach, beforeEach, expect, it, vi } from "vitest";
vi.mock("./container-runner.js", () => ({ wakeContainer: vi.fn() }));
vi.mock("./session-manager.js", () => ({
  resolveSession: vi.fn(),
  writeSessionMessage: vi.fn(),
  writeOutboundDirect: vi.fn(),
}));
vi.mock("./channels/channel-registry.js", () => ({
  getChannelAdapter: vi.fn(),
}));
import { routeInbound, registerMessageInterceptor } from "./router.js";
import { wakeContainer } from "./container-runner.js";
import { resolveSession, writeSessionMessage } from "./session-manager.js";
import type { InboundEvent } from "./channels/adapter.js";

let responder: (event: InboundEvent) => void;
registerMessageInterceptor(async (event) => {
  responder(event);
  return true;
});
beforeEach(() => {
  vi.clearAllMocks(); process.env.WHATSAPP_LOOP_GUARD='1';
  const db=initTestDb();db.exec('CREATE TABLE agent_groups(id TEXT PRIMARY KEY)');migration027.up(db);
  registerWhatsAppAccount('whatsapp','15551110001');registerWhatsAppAccount('whatsapp-cloud','15551110002');
});
afterEach(() => { delete process.env.WHATSAPP_LOOP_GUARD;closeDb(); });

async function simulate(start: "A" | "B", enabled: boolean) {
  if (!enabled) delete process.env.WHATSAPP_LOOP_GUARD;
  let crossings = 0,
    turns = 0;
  const queue: InboundEvent[] = [];
  // Provider adapters deliberately strip internal metadata and create fresh IDs.
  const send = (from: "A" | "B", text: string) => {
    crossings++;
    const phone = from === "A" ? "15551110001" : "15551110002";
    const cloud = from === "B";
    queue.push({
      channelType: "whatsapp",
      instance: cloud ? "whatsapp-cloud" : "whatsapp",
      platformId: cloud
        ? `whatsapp:998877:${phone}`
        : `${phone}@s.whatsapp.net`,
      threadId: null,
      message: {
        id: `fresh-provider-${crossings}`,
        kind: cloud ? "chat-sdk" : "chat",
        timestamp: "2026-01-01T00:00:00Z",
        content: JSON.stringify(
          cloud
            ? { senderId: phone, text: text.replaceAll("**", "*") }
            : {
                sender: `${phone}@s.whatsapp.net`,
                text: text.replaceAll("**", "*"),
                fromMe: false,
                isBotMessage: false,
              },
        ),
      },
    });
  };
  responder = (e) => {
    turns++;
    send(
      e.instance === "whatsapp" ? "B" : "A",
      `**New agent response ${turns}**`,
    );
  };
  // Initial output generated by A (or B) after a human request.
  send(start, "**Initial output**");
  while (queue.length && turns < 8) await routeInbound(queue.shift()!);
  return { crossings, turns, pending: queue.length };
}
it.each(["A", "B"] as const)(
  "stops the two-account loop after exactly one external hop, starting at %s",
  async (start) => {
    expect(await simulate(start, true)).toEqual({
      crossings: 1,
      turns: 0,
      pending: 0,
    });
    expect(resolveSession).not.toHaveBeenCalled();
    expect(writeSessionMessage).not.toHaveBeenCalled();
    expect(wakeContainer).not.toHaveBeenCalled();
  },
);
it("negative control reproduces an unbounded exchange, capped by the test harness", async () => {
  expect(await simulate("A", false)).toEqual({
    crossings: 9,
    turns: 8,
    pending: 1,
  });
});
it("missing registry fails before any responder or wake", async () => {
  getDb().exec('DROP TABLE whatsapp_agent_bindings');
  await expect(simulate("A", true)).rejects.toThrow();
  expect(wakeContainer).not.toHaveBeenCalled();
});
